### ISSUE TITLE
postgres save error: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by avelino** [okfn-brasil/diario-oficial#145]
When **running crawler the second** time a duplicity exception is generated in the Postgres

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/mnt/code/data_collection/gazette/pipelines.py", line 28, in process_item
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2596, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2556, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "gazettes_territory_id_date_file_checksum_key"
DETAIL:  Key (territory_id, date, file_checksum)=(3509502, 2016-09-01, 6509975a6cba06faa73eb0b463acea30) already exists.

[SQL: INSERT INTO gazettes (source_text, date, is_extra_edition, is_parsed, power, file_checksum, file_path, file_url, scraped_at, created_at, territory_id) VALUES (%(source_text)s, %(date)s, %(is_extra_edition)s, %(is_parsed)s, %(power)s, %(file_checksum)s, %(file_path)s, %(file_url)s, %(scraped_at)s, %(created_at)s, %(territory_id)s) RETURNING gazettes.id]
[parameters: {'source_text': 'Nº 11.431 - Ano XLV\n                           Diário Oficial                     Quinta-feira, 01 de setembro de 2016                               ... (1320312 characters truncated) ... . - Alteração da forma de cobrança\n                                                                                       da taxa de material.\n\x0c', 'date': datetime.date(2016, 9, 1), 'is_extra_edition': False, 'is_parsed': False, 'power': 'executive_legislature', 'file_checksum': '6509975a6cba06faa73eb0b463acea30', 'file_path': 'full/4abcf9e6df73b424f8e3b38140a3062af85b4800.pdf', 'file_url': 'http://www.campinas.sp.gov.br/uploads/pdf/2118544071.pdf', 'scraped_at': datetime.datetime(2019, 12, 6, 17, 40, 55, 19918), 'created_at': datetime.datetime(2019, 12, 6, 17, 41, 1, 688711), 'territory_id': '3509502'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by jvanz** [comment]
Yeah, I was thinking to change that while I was working in the FECAM spider. I believe we can add a simple verification to see if the spider is already in the database or any similar thing. Just to avoid this ugly error

**Comment by feliperuhland** [comment]
What about just manage that exception and write a log explaining that record was already saved?

**Comment by jvanz** [comment]
> What about just manage that exception and write a log explaining that record was already saved?

Yeah, sounds good to me. Are you willing to do that? :)

**Comment by feliperuhland** [comment]
Sure!
